version: '3.1'
services:
  alura-challenges-api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/alura-challenges-2
      - /home/alura-challenges-2/node_modules
    env_file: '.env'
    container_name: alura-challenges-api
    links:
      - db
    depends_on:
      - db
    networks:
      - alura-challenges-network

  #  frontend:
  #    build: ../vehicle-catalog-ui
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ../vehicle-catalog-ui:/home/ui
  #      - /home/ui/node_modules
  #    container_name: vehicles_ui
  #    links:
  #    - backend
  #    depends_on:
  #    - backend
  #    networks:
  #      - alura-challenges-network

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=alura_challenge'
      - 'MYSQL_USER=homestead'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_PORT=3306'
    ports:
      - '3306:3306'
    container_name: db
    networks:
      - alura-challenges-network

volumes:
  dbdata:

networks:
  alura-challenges-network:
